-- LINDA Config file for RealAir Duke Turbine V2
-- Generated by LINDA Configurator at 1508161152


-- ############################################### --
-- ## AEFIS block mode1
-- ############################################### --

-- AEFIS block buttons and switches
EFIS1 = {
["ENABLED"] = true  ,
["IDENT"]   = "Std"  ,
["InHg."]   = Efis_INHG  ,
["hPa ."]   = Efis_HPA  ,
["FD  ."]   = Autopilot_FD_on  ,
["ILS ."]   = Autopilot_LOC_hold  ,
["CSTR."]   = Efis_CSTR_button  ,
["WPT ."]   = Efis_WPT_button  ,
["VORD."]   = Efis_VORD_button  ,
["NDB ."]   = Efis_NDB_button  ,
["ARPT."]   = Efis_ARPT_button  ,
["ADF1:"]   = empty  ,
["ADF1."]   = empty  ,
["VOR1:"]   = empty  ,
["VOR1."]   = empty  ,
["ADF2:"]   = empty  ,
["ADF2."]   = empty  ,
["VOR2:"]   = empty  ,
["VOR2."]   = empty  ,
}

-- AEFIS BARO knob
BARO1 = {
["A SHOW"]  = Altimeter_BARO_show  ,
["A  +"]    = Altimeter_BARO_plus  ,
["A ++"]    = Altimeter_BARO_plusfast  ,
["A  -"]    = Altimeter_BARO_minus  ,
["A --"]    = Altimeter_BARO_minusfast  ,
["PRESS"]   = Altimeter_BARO_MODE_toggle  ,
["B SHOW"]  = empty  ,
["B  +"]    = empty  ,
["B ++"]    = empty  ,
["B  -"]    = empty  ,
["B --"]    = empty  ,
}

-- AEFIS NDM knob
NDM1 = {
["A SHOW"]  = empty  ,
["A  +"]    = empty  ,
["A ++"]    = empty  ,
["A  -"]    = empty  ,
["A --"]    = empty  ,
["PRESS"]   = empty  ,
["B SHOW"]  = empty  ,
["B  +"]    = empty  ,
["B ++"]    = empty  ,
["B  -"]    = empty  ,
["B --"]    = empty  ,
}

-- AEFIS NDR knob
NDR1 = {
["A SHOW"]  = empty  ,
["A  +"]    = CowlFlaps_inc  ,
["A ++"]    = CowlFlaps_inc  ,
["A  -"]    = CowlFlaps_dec  ,
["A --"]    = CowlFlaps_dec  ,
["PRESS"]   = empty  ,
["B SHOW"]  = empty  ,
["B  +"]    = empty  ,
["B ++"]    = empty  ,
["B  -"]    = empty  ,
["B --"]    = empty  ,
}

-- ############################################### --
-- ## AEFIS block mode2
-- ############################################### --

-- AEFIS block buttons and switches
EFIS2 = {
["ENABLED"] = true  ,
["IDENT"]   = "empty"  ,
["InHg."]   = empty  ,
["hPa ."]   = empty  ,
["FD  ."]   = empty  ,
["ILS ."]   = empty  ,
["CSTR."]   = empty  ,
["WPT ."]   = empty  ,
["VORD."]   = empty  ,
["NDB ."]   = empty  ,
["ARPT."]   = empty  ,
["ADF1:"]   = empty  ,
["ADF1."]   = empty  ,
["VOR1:"]   = empty  ,
["VOR1."]   = empty  ,
["ADF2:"]   = empty  ,
["ADF2."]   = empty  ,
["VOR2:"]   = empty  ,
["VOR2."]   = empty  ,
}

-- AEFIS BARO knob
BARO2 = {
["A SHOW"]  = empty  ,
["A  +"]    = empty  ,
["A ++"]    = empty  ,
["A  -"]    = empty  ,
["A --"]    = empty  ,
["PRESS"]   = empty  ,
["B SHOW"]  = empty  ,
["B  +"]    = empty  ,
["B ++"]    = empty  ,
["B  -"]    = empty  ,
["B --"]    = empty  ,
}

-- AEFIS NDM knob
NDM2 = {
["A SHOW"]  = empty  ,
["A  +"]    = empty  ,
["A ++"]    = empty  ,
["A  -"]    = empty  ,
["A --"]    = empty  ,
["PRESS"]   = empty  ,
["B SHOW"]  = empty  ,
["B  +"]    = empty  ,
["B ++"]    = empty  ,
["B  -"]    = empty  ,
["B --"]    = empty  ,
}

-- AEFIS NDR knob
NDR2 = {
["A SHOW"]  = empty  ,
["A  +"]    = empty  ,
["A ++"]    = empty  ,
["A  -"]    = empty  ,
["A --"]    = empty  ,
["PRESS"]   = empty  ,
["B SHOW"]  = empty  ,
["B  +"]    = empty  ,
["B ++"]    = empty  ,
["B  -"]    = empty  ,
["B --"]    = empty  ,
}

-- ############################################### --
-- ## AEFIS block mode3
-- ############################################### --

-- AEFIS block buttons and switches
EFIS3 = {
["ENABLED"] = false  ,
["IDENT"]   = "empty"  ,
["InHg."]   = empty  ,
["hPa ."]   = empty  ,
["FD  ."]   = empty  ,
["ILS ."]   = empty  ,
["CSTR."]   = empty  ,
["WPT ."]   = empty  ,
["VORD."]   = empty  ,
["NDB ."]   = empty  ,
["ARPT."]   = empty  ,
["ADF1:"]   = empty  ,
["ADF1."]   = empty  ,
["VOR1:"]   = empty  ,
["VOR1."]   = empty  ,
["ADF2:"]   = empty  ,
["ADF2."]   = empty  ,
["VOR2:"]   = empty  ,
["VOR2."]   = empty  ,
}

-- AEFIS BARO knob
BARO3 = {
["A SHOW"]  = empty  ,
["A  +"]    = empty  ,
["A ++"]    = empty  ,
["A  -"]    = empty  ,
["A --"]    = empty  ,
["PRESS"]   = empty  ,
["B SHOW"]  = empty  ,
["B  +"]    = empty  ,
["B ++"]    = empty  ,
["B  -"]    = empty  ,
["B --"]    = empty  ,
}

-- AEFIS NDM knob
NDM3 = {
["A SHOW"]  = empty  ,
["A  +"]    = empty  ,
["A ++"]    = empty  ,
["A  -"]    = empty  ,
["A --"]    = empty  ,
["PRESS"]   = empty  ,
["B SHOW"]  = empty  ,
["B  +"]    = empty  ,
["B ++"]    = empty  ,
["B  -"]    = empty  ,
["B --"]    = empty  ,
}

-- AEFIS NDR knob
NDR3 = {
["A SHOW"]  = empty  ,
["A  +"]    = empty  ,
["A ++"]    = empty  ,
["A  -"]    = empty  ,
["A --"]    = empty  ,
["PRESS"]   = empty  ,
["B SHOW"]  = empty  ,
["B  +"]    = empty  ,
["B ++"]    = empty  ,
["B  -"]    = empty  ,
["B --"]    = empty  ,
}

-- ############################################### --
-- ## AFCU block mode1
-- ############################################### --

-- AFCU block buttons and switches
MCP1 = {
["ENABLED"] 	= true  ,
["IDENT"]   	= "MCP1"  ,
["MACH."]   	= Autopilot_MACH_button  ,
["LOC ."]   	= Autopilot_LOC_button  ,
["TRK ."]   	= Autopilot_TRK_button  ,
["AP1 ."]   	= "FSX:_AP_MASTER:0"  ,
["AP2 ."]   	= Autopilot_AP2_button  ,
["ATHR."]   	= Autopilot_AIRSPEED_hold  ,
["EXPD."]   	= Autopilot_EXPD_button  ,
["MTR ."]   	= Autopilot_MTR_button  ,
["APPR."]   	= Autopilot_APR_hold  ,
}

-- AFCU SPD knob
SPD1 = {
["A SHOW"]  	= SPD_show  ,
["A  +"]    	= SPD_plus  ,
["A ++"]    	= SPD_plusfast  ,
["A  -"]    	= SPD_minus  ,
["A --"]    	= SPD_minusfast  ,
["PRESS"]   	= Autopilot_AIRSPEED_hold  ,
["PULL"]    	= SPD_pull  ,
}

-- AFCU HDG knob
HDG1 = {
["A SHOW"]  	= HDG_show  ,
["A  +"]    	= HDG_plus  ,
["A ++"]    	= HDG_plusfast  ,
["A  -"]    	= HDG_minus  ,
["A --"]    	= HDG_minusfast  ,
["PRESS"]   	= Autopilot_HDG_hold  ,
["PULL"]    	= Autopilot_PANEL_HDG_hold  ,
}

-- AFCU ALT knob
ALT1 = {
["A SHOW"]  	= ALT_show  ,
["A  +"]    	= ALT_plus  ,
["A ++"]    	= ALT_plusfast  ,
["A  -"]    	= ALT_minus  ,
["A --"]    	= ALT_minusfast  ,
["PRESS"]   	= Autopilot_ALT_hold  ,
["PULL"]    	= ALT_pull  ,
}

-- AFCU VVS knob
VVS1 = {
["A SHOW"]  	= VVS_show  ,
["A  +"]    	= VVS_plus  ,
["A ++"]    	= VVS_plusfast  ,
["A  -"]    	= VVS_minus  ,
["A --"]    	= VVS_minusfast  ,
["PRESS"]   	= VVS_press  ,
["PULL"]    	= VVS_pull  ,
}


-- ############################################### --
-- ## AFCU block mode2
-- ############################################### --

-- AFCU block buttons and switches
MCP2 = {
["ENABLED"] 	= true  ,
["IDENT"]   	= "MCP2"  ,
["MACH."]   	= Autopilot_MACH_button  ,
["LOC ."]   	= Autopilot_LOC_button  ,
["TRK ."]   	= Autopilot_TRK_button  ,
["AP1 ."]   	= Autopilot_AP1_button  ,
["AP2 ."]   	= Autopilot_AP2_button  ,
["ATHR."]   	= Autopilot_ATHR_button  ,
["EXPD."]   	= Autopilot_EXPD_button  ,
["MTR ."]   	= Autopilot_MTR_button  ,
["APPR."]   	= Autopilot_APPR_button  ,
}

-- AFCU SPD knob
SPD2 = {
["A SHOW"]  	= SPD_show  ,
["A  +"]    	= SPD_plus  ,
["A ++"]    	= SPD_plusfast  ,
["A  -"]    	= SPD_minus  ,
["A --"]    	= SPD_minusfast  ,
["PRESS"]   	= SPD_press  ,
["PULL"]    	= SPD_pull  ,
}

-- AFCU HDG knob
HDG2 = {
["A SHOW"]  	= HDG_show  ,
["A  +"]    	= HDG_plus  ,
["A ++"]    	= HDG_plusfast  ,
["A  -"]    	= HDG_minus  ,
["A --"]    	= HDG_minusfast  ,
["PRESS"]   	= HDG_press  ,
["PULL"]    	= HDG_pull  ,
}

-- AFCU ALT knob
ALT2 = {
["A SHOW"]  	= ALT_show  ,
["A  +"]    	= ALT_plus  ,
["A ++"]    	= ALT_plusfast  ,
["A  -"]    	= ALT_minus  ,
["A --"]    	= ALT_minusfast  ,
["PRESS"]   	= ALT_press  ,
["PULL"]    	= ALT_pull  ,
}

-- AFCU VVS knob
VVS2 = {
["A SHOW"]  	= VVS_show  ,
["A  +"]    	= VVS_plus  ,
["A ++"]    	= VVS_plusfast  ,
["A  -"]    	= VVS_minus  ,
["A --"]    	= VVS_minusfast  ,
["PRESS"]   	= VVS_press  ,
["PULL"]    	= VVS_pull  ,
}


-- ############################################### --
-- ## AFCU block mode3
-- ############################################### --

-- AFCU block buttons and switches
MCP3 = {
["ENABLED"] 	= false  ,
["IDENT"]   	= "MCP3"  ,
["MACH."]   	= Autopilot_MACH_button  ,
["LOC ."]   	= Autopilot_LOC_button  ,
["TRK ."]   	= Autopilot_TRK_button  ,
["AP1 ."]   	= Autopilot_AP1_button  ,
["AP2 ."]   	= Autopilot_AP2_button  ,
["ATHR."]   	= Autopilot_ATHR_button  ,
["EXPD."]   	= Autopilot_EXPD_button  ,
["MTR ."]   	= Autopilot_MTR_button  ,
["APPR."]   	= Autopilot_APPR_button  ,
}

-- AFCU SPD knob
SPD3 = {
["A SHOW"]  	= SPD_show  ,
["A  +"]    	= SPD_plus  ,
["A ++"]    	= SPD_plusfast  ,
["A  -"]    	= SPD_minus  ,
["A --"]    	= SPD_minusfast  ,
["PRESS"]   	= SPD_press  ,
["PULL"]    	= SPD_pull  ,
}

-- AFCU HDG knob
HDG3 = {
["A SHOW"]  	= HDG_show  ,
["A  +"]    	= HDG_plus  ,
["A ++"]    	= HDG_plusfast  ,
["A  -"]    	= HDG_minus  ,
["A --"]    	= HDG_minusfast  ,
["PRESS"]   	= HDG_press  ,
["PULL"]    	= HDG_pull  ,
}

-- AFCU ALT knob
ALT3 = {
["A SHOW"]  	= ALT_show  ,
["A  +"]    	= ALT_plus  ,
["A ++"]    	= ALT_plusfast  ,
["A  -"]    	= ALT_minus  ,
["A --"]    	= ALT_minusfast  ,
["PRESS"]   	= ALT_press  ,
["PULL"]    	= ALT_pull  ,
}

-- AFCU VVS knob
VVS3 = {
["A SHOW"]  	= VVS_show  ,
["A  +"]    	= VVS_plus  ,
["A ++"]    	= VVS_plusfast  ,
["A  -"]    	= VVS_minus  ,
["A --"]    	= VVS_minusfast  ,
["PRESS"]   	= VVS_press  ,
["PULL"]    	= VVS_pull  ,
}


-- ############################################### --
-- ## AUSER block mode1
-- ############################################### --

-- AUSER block buttons and switches
USER1 = {
["ENABLED"] = true  ,
["IDENT"]   = "Lght"  ,
["BTN1."]   = Ignition_L_toggle_OffAuto  ,
["BTN2."]   = Lights_TAXI_toggle  ,
["BTN3."]   = Ignition_R_toggle_OffAuto  ,
["BTN4."]   = "FSX:_TOGGLE_STARTER1:0"  ,
["BTN5."]   = ParkingBreakesToggle  ,
["BTN6."]   = "FSX:_TOGGLE_STARTER2:0"  ,
["BTN7."]   = "Control:_66340:0"  ,
["BTN8."]   = "Control:_66341:0"  ,
["USR1."]   = CowlFlaps_BOTH_open  ,
["USR2."]   = empty  ,
["USR3."]   = empty  ,
["USR4."]   = empty  ,
["USR5."]   = empty  ,
["USR6."]   = DukeB60_Inverter_toggle  ,
["USR7."]   = Battery_toggle  ,
["USR8."]   = "Control:_66293:0"  ,
}

-- ############################################### --
-- ## AUSER block mode2
-- ############################################### --

-- AUSER block buttons and switches
USER2 = {
["ENABLED"] = true  ,
["IDENT"]   = "USR2"  ,
["BTN1."]   = empty  ,
["BTN2."]   = empty  ,
["BTN3."]   = empty  ,
["BTN4."]   = empty  ,
["BTN5."]   = empty  ,
["BTN6."]   = VRI_EFIS_MODE_toggle  ,
["BTN7."]   = VRI_MCP_MODE_toggle  ,
["BTN8."]   = VRI_USER_MODE_toggle  ,
["USR1."]   = empty  ,
["USR2."]   = empty  ,
["USR3."]   = empty  ,
["USR4."]   = empty  ,
["USR5."]   = empty  ,
["USR6."]   = empty  ,
["USR7."]   = empty  ,
["USR8."]   = empty  ,
}

-- ############################################### --
-- ## AUSER block mode3
-- ############################################### --

-- AUSER block buttons and switches
USER3 = {
["ENABLED"] = true  ,
["IDENT"]   = "USR3"  ,
["BTN1."]   = empty  ,
["BTN2."]   = empty  ,
["BTN3."]   = empty  ,
["BTN4."]   = empty  ,
["BTN5."]   = empty  ,
["BTN6."]   = VRI_EFIS_MODE_toggle  ,
["BTN7."]   = VRI_MCP_MODE_toggle  ,
["BTN8."]   = VRI_USER_MODE_toggle  ,
["USR1."]   = empty  ,
["USR2."]   = empty  ,
["USR3."]   = empty  ,
["USR4."]   = empty  ,
["USR5."]   = empty  ,
["USR6."]   = empty  ,
["USR7."]   = empty  ,
["USR8."]   = empty  ,
}

-- ############################################### --
-- ## ARADIOS block mode1
-- ############################################### --

-- RADIOS block buttons and switches
RADIOS = {
["COM ."]	= Default_COM_select  ,
["NAV ."]	= Default_NAV_select  ,
["ADF ."]	= Default_ADF_select  ,
["DME ."]	= Default_DME_select  ,
["TRAN."]	= Default_XPND_select  ,
["TFR ."]	= Default_RADIOS_swap  ,
["STBY."]	= Default_RADIOS_mode  ,
["LAMP."]   	= Default_LAMP_toggle ,

["COM1 Select"] = empty  ,
["COM2 Select"] = empty  ,
["COM1 Swap"]   = empty  ,
["COM2 Swap"]   = empty  ,
["COMs Mode"]   = Radios_COM_AUDIO_toggle  ,

["NAV1 Select"] = empty  ,
["NAV2 Select"] = empty  ,
["NAV1 Swap"]   = empty  ,
["NAV2 Swap"]   = empty  ,
["NAVs Mode"]   = Radios_NAV_AUDIO_toggle  ,

["ADF1 Select"] = empty  ,
["ADF2 Select"] = empty  ,
["ADFs Mode"]   = Radios_ADF_AUDIO_toggle  ,

["DME1 Select"] = empty  ,
["DME2 Select"] = empty  ,
["DMEs Mode"]   = Radios_DME_AUDIO_toggle  ,

["XPND Select"] = empty  ,
["XPND Swap"]   = empty  ,
["XPND Mode"]   = Transponder_MODE_toggle  ,
}

DME1 = {
["A  +"]   	= empty  ,
["A ++"]   	= empty  ,
["A  -"]   	= empty  ,
["A --"]   	= empty  ,
["PRESS"]  	= empty  ,
}

FRE1 = {
["A  +"]   	= Default_RADIOS_plus  ,
["A ++"]   	= Default_RADIOS_plusfast  ,
["A  -"]   	= Default_RADIOS_minus  ,
["A --"]   	= Default_RADIOS_minusfast  ,
["PRESS"]  	= Default_RADIOS_press  ,
}

